name: Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPUS_VERSION: 1.3.1
      NDK_VERSION: r26d
      ANDROID_API: 21
      TARGET_ARCH: arm64-v8a

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config

      - name: Download and set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
          unzip android-ndk-${NDK_VERSION}-linux.zip
          echo "NDK_DIR=$PWD/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
          echo "TOOLCHAIN=$PWD/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV

      - name: Download libopus
        run: |
          wget https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz
          tar xzf opus-${OPUS_VERSION}.tar.gz

      - name: Build libopus with NDK
        run: |
          export TOOLCHAIN=$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=$ANDROID_API
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export AR=$TOOLCHAIN/bin/llvm-ar
          
          cd opus-${OPUS_VERSION}
          ./configure \
            --prefix=$HOME/libopus-prefix \
            --host=$TARGET \
            --enable-static \
            --disable-shared \
            CC=$CC \
            AR=$AR \
            CFLAGS="--sysroot=$TOOLCHAIN/sysroot"
          make -j$(nproc)
          make install

      - name: Set up pkg-config for libopus
        run: |          
          echo "PKG_CONFIG_PATH=$HOME/libopus-prefix/lib/pkgconfig" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "GOOS=android" >> $GITHUB_ENV
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "CC=$TOOLCHAIN/bin/aarch64-linux-android$ANDROID_API-clang" >> $GITHUB_ENV
          echo "CGO_CFLAGS=--sysroot=$TOOLCHAIN/sysroot" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$HOME/libopus-prefix/lib -lopus" >> $GITHUB_ENV

      - name: Build Go binary for Android
        run: |
          pkg-config --cflags opus
          pkg-config --libs opus
          cd src && go build -v -o ../android-arm64-server

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-server
          path: android-arm64-server