name: Build Go binary for Linux

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx (for multi-arch support)
        uses: docker/setup-buildx-action@v2

      - name: Build and run AMD64 golang container to compile
        run: |
          docker run --rm --platform linux/amd64 \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            golang:1.24.2-alpine /bin/sh -c 'apk add --no-cache musl-dev gcc pkgconfig opus-dev && go mod tidy && cd src && CGO_CFLAGS="-I opus/include" CGO_LDFLAGS="-L opus/library/linux/amd64 -lopus -lm" CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-extldflags \"-static\"" -o ../linux-amd64-server -v'

      - name: Upload AMD64 binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-server
          path: linux-amd64-server
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx (for multi-arch support)
        uses: docker/setup-buildx-action@v2

      - name: Build and run ARM64 golang container to compile
        run: |
          docker run --rm --platform linux/arm64 \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            golang:1.24.2-alpine /bin/sh -c 'apk add --no-cache musl-dev gcc pkgconfig opus-dev && go mod tidy && cd src && CGO_CFLAGS="-I opus/include" CGO_LDFLAGS="-L opus/library/linux/arm64 -lopus -lm" CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags="-extldflags \"-static\"" -o ../linux-arm64-server -v'

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-server
          path: linux-arm64-server