name: Build Go binary on Alpine

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx (for multi-arch support)
        uses: docker/setup-buildx-action@v2

      - name: Build and run ARM64 golang container to compile
        run: |
          docker run --rm --platform linux/arm64 \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            golang:1.24.2-alpine /bin/sh -c '
              apk add --no-cache musl-dev gcc && go mod tidy && ls -la && cd src && ls -la && /bin/sh ./build/build-linux-arm64.sh
            '

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-server
          path: linux-arm64-server